<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INFO-IN-LTP-061" ignored="0" name="Default test" tests="3" failures="1" timestamp="11 Feb 2022 02:55:40 GMT" time="312.799" errors="0">
  <testcase name="runScenario" time="168.995" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="47.589" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1:00] but found [2:00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1:00] but found [2:00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at info.stepdefinition.UpdateByIndividual.user_verify_the_changes_in_update_by_individual(UpdateByIndividual.java:707)
at âœ½.User verify the changes in update by individual "Update By Individual" and 0(file:///C:/Users/Sheik%20Mohammed/eclipse-workspace/info/src/test/resources/Features/UpdateByIndividual.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="95.437" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Default test -->
